// Bucket List: Australian Birds — Card Definitions
// Generated from CSV data

export const HABITATS = [
  'Rainforest',
  'Bushland & Scrub',
  'Wetlands & Waterways',
  'Coastal & Ocean',
  'Outback & Grassland',
];

export const DIETS = [
  'Seeds & Grain',
  'Nectar & Fruit',
  'Insects & Invertebrates',
  'Fish & Aquatic Prey',
  'Meat & Carrion',
];

export const HABITAT_COLORS = {
  'Rainforest': { gradient: '#1A4731-#2D6A4F', display: 'deep emerald' },
  'Bushland & Scrub': { gradient: '#7C5213-#A0692E', display: 'eucalyptus ochre' },
  'Wetlands & Waterways': { gradient: '#0F4C65-#1B6E8A', display: 'deep teal' },
  'Coastal & Ocean': { gradient: '#0C3264-#1E4DA0', display: 'ocean navy' },
  'Outback & Grassland': { gradient: '#8B3A0A-#B4541F', display: 'burnt terracotta' },
  'WILD': { gradient: '#4C1D95-#6D28D9', display: 'purple' },
};

export const DIET_COLORS = {
  'Seeds & Grain': '#D97706',
  'Nectar & Fruit': '#BE185D',
  'Insects & Invertebrates': '#047857',
  'Fish & Aquatic Prey': '#0369A1',
  'Meat & Carrion': '#B91C1C',
  'WILD': '#7C3AED',
};

// Icon filename mappings
export const ICON_MAP = {
  'Rainforest': 'category_rainforest.png',
  'Bushland & Scrub': 'category_scrub.png',
  'Wetlands & Waterways': 'category_wetlands.png',
  'Coastal & Ocean': 'category_ocean.png',
  'Outback & Grassland': 'category_outback.png',
  'WILD_HABITAT': 'category_wild.png',
  'Seeds & Grain': 'category_seeds.png',
  'Nectar & Fruit': 'category_fruit.png',
  'Insects & Invertebrates': 'category_insects.png',
  'Fish & Aquatic Prey': 'category_fish.png',
  'Meat & Carrion': 'category_carnivore.png',
  'WILD_DIET': 'category_wild.png',
};

export const AUSTRALIAN_BIRDS = [
  { id: 1, name: 'King Parrot', fact: 'Males take 3 years to turn fully red', habitat: 'Rainforest', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 2, name: 'Double-eyed Fig-Parrot', fact: "Australia's smallest parrot at just 14cm", habitat: 'Rainforest', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 3, name: 'Wompoo Pigeon', fact: 'Can swallow whole fruits bigger than its head', habitat: 'Rainforest', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 4, name: 'Regent Bowerbird', fact: "Mixes its own paint to decorate its bower", habitat: 'Rainforest', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 5, name: 'Noisy Pitta', fact: "Smashes snails on a favourite rock 'anvil'", habitat: 'Rainforest', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 6, name: 'Rufous Fantail', fact: 'Fans its tail to startle insects into flight', habitat: 'Rainforest', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 7, name: 'Azure Kingfisher', fact: 'Beats fish against a branch before eating', habitat: 'Rainforest', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 8, name: 'Green Pygmy Goose', fact: "Not a goose at all – it's a tiny perching duck", habitat: 'Rainforest', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 9, name: 'Grey Goshawk', fact: "Australia's only pure white bird of prey", habitat: 'Rainforest', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 10, name: 'Rufous Owl', fact: 'Can catch possums and sugar gliders mid-air', habitat: 'Rainforest', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 11, name: 'Eastern Crimson Rosella', fact: "Some populations are yellow, not crimson", habitat: 'Bushland & Scrub', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 12, name: 'Sulphur-crested Cockatoo', fact: 'Can live over 80 years in captivity', habitat: 'Bushland & Scrub', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 13, name: 'Scarlet Honeyeater', fact: 'Weighs less than two teaspoons of sugar', habitat: 'Bushland & Scrub', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 14, name: 'Rainbow Lorikeet', fact: 'Has a brush-tipped tongue for licking nectar', habitat: 'Bushland & Scrub', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 15, name: 'Splendid Fairywren', fact: 'Males bring petals to females as courtship gifts', habitat: 'Bushland & Scrub', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 16, name: 'Red-capped Robin', fact: 'Can spot a moving insect from 40 metres away', habitat: 'Bushland & Scrub', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 17, name: 'Laughing Kookaburra', fact: 'Its laugh marks territory at dawn and dusk', habitat: 'Bushland & Scrub', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 18, name: 'Sacred Kingfisher', fact: 'Nests inside termite mounds in tree trunks', habitat: 'Bushland & Scrub', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 19, name: 'Powerful Owl', fact: "Roosts all day clutching last night's catch", habitat: 'Bushland & Scrub', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 20, name: 'Barking Owl', fact: 'Screaming call once mistaken for a woman', habitat: 'Bushland & Scrub', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 21, name: 'Black Swan', fact: "Once thought impossible – now WA's emblem", habitat: 'Wetlands & Waterways', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 22, name: 'Magpie Goose', fact: 'A living fossil with half-webbed feet', habitat: 'Wetlands & Waterways', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 23, name: 'Spinebill', fact: 'Can hover like a hummingbird at flowers', habitat: 'Wetlands & Waterways', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 24, name: "Lewin's Honeyeater", fact: 'Named after a convict ship artist in 1801', habitat: 'Wetlands & Waterways', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 25, name: 'Rainbow Bee-eater', fact: 'Rubs bee stings off on a branch before eating', habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 26, name: 'Royal Spoonbill', fact: 'Sweeps its spoon-shaped bill side to side', habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 27, name: 'Nankeen Night Heron', fact: "Hunts by moonlight, sleeps hidden by day", habitat: 'Wetlands & Waterways', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 28, name: 'Australian Pelican', fact: 'Has the longest bill of any living bird', habitat: 'Wetlands & Waterways', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 29, name: 'Swamp Harrier', fact: 'Passes food to its mate mid-flight', habitat: 'Wetlands & Waterways', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 30, name: 'White-faced Heron', fact: 'Vibrates its foot underwater to lure prey', habitat: 'Wetlands & Waterways', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 31, name: 'Crested Pigeon', fact: 'Its wings make a whistling alarm when it takes off', habitat: 'Coastal & Ocean', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 32, name: 'Bush Stone-curlew', fact: 'Freezes statue-still when threatened', habitat: 'Coastal & Ocean', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 33, name: 'Noisy Friarbird', fact: "Bald black head earned it the name 'leatherhead'", habitat: 'Coastal & Ocean', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 34, name: 'Little Wattlebird', fact: "Named 'little' but is actually 30cm long", habitat: 'Coastal & Ocean', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 35, name: 'Sooty Oystercatcher', fact: 'Uses its bill like a chisel on rock oysters', habitat: 'Coastal & Ocean', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 36, name: 'Pied Oystercatcher', fact: 'Chicks can swim within hours of hatching', habitat: 'Coastal & Ocean', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 37, name: 'White-bellied Sea Eagle', fact: 'Mates lock talons and cartwheel through the sky', habitat: 'Coastal & Ocean', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 38, name: 'Australasian Gannet', fact: 'Plunge-dives from 30 metres at 100 km/h', habitat: 'Coastal & Ocean', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 39, name: 'Brahminy Kite', fact: 'Sacred in Hindu mythology as Vishnu\'s bird', habitat: 'Coastal & Ocean', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 40, name: 'Pacific Gull', fact: 'Drops shellfish from height to crack them open', habitat: 'Coastal & Ocean', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 41, name: 'Gouldian Finch', fact: "Comes in red, black, or yellow-headed forms", habitat: 'Outback & Grassland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 42, name: 'Princess Parrot', fact: 'May vanish from an area for 20 years', habitat: 'Outback & Grassland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 43, name: 'Crimson Chat', fact: 'Fakes a broken wing to lure predators away', habitat: 'Outback & Grassland', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 44, name: 'Pied Honeyeater', fact: 'Performs a spectacular spiralling song flight', habitat: 'Outback & Grassland', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 45, name: 'Nankeen Kestrel', fact: 'Hovers perfectly still in wind like a drone', habitat: 'Outback & Grassland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 46, name: 'Budgerigar', fact: "Wild flocks can number over 10,000 birds", habitat: 'Outback & Grassland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 47, name: 'Brolga', fact: 'Famous for its elaborate courtship dance', habitat: 'Outback & Grassland', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 48, name: 'Black-necked Stork', fact: "Australia's only stork – often called Jabiru", habitat: 'Outback & Grassland', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 49, name: 'Wedge-tailed Eagle', fact: '2.3m wingspan – can soar for hours unseen', habitat: 'Outback & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 50, name: 'Crow', fact: 'Can solve multi-step puzzles for food', habitat: 'Outback & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 51, name: 'Southern Cassowary', fact: 'Its kick can be lethal to humans', habitat: 'Rainforest', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 52, name: 'Superb Lyrebird', fact: "Can mimic chainsaws, cameras, and car alarms", habitat: 'Bushland & Scrub', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 53, name: 'Purple Swamphen', fact: 'Holds food in one foot like a hand to eat', habitat: 'Wetlands & Waterways', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 54, name: 'Little Penguin', fact: "World's smallest penguin at just 33cm tall", habitat: 'Coastal & Ocean', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 55, name: 'Emu', fact: 'Dad sits on the eggs and raises chicks alone', habitat: 'Outback & Grassland', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 56, name: 'Galah', fact: "Aussie slang for a fool is named after it", habitat: 'WILD', diet: 'Seeds & Grain', isWildHabitat: true, isWildDiet: false },
  { id: 57, name: 'Figbird', fact: 'Males have bright red bare skin around eyes', habitat: 'WILD', diet: 'Nectar & Fruit', isWildHabitat: true, isWildDiet: false },
  { id: 58, name: 'Satin Bowerbird', fact: 'Obsessively collects anything blue for its bower', habitat: 'WILD', diet: 'Insects & Invertebrates', isWildHabitat: true, isWildDiet: false },
  { id: 59, name: 'Darter', fact: 'Swims with only its snake-like neck showing', habitat: 'WILD', diet: 'Fish & Aquatic Prey', isWildHabitat: true, isWildDiet: false },
  { id: 60, name: 'Peregrine Falcon', fact: 'Fastest animal on Earth at 390 km/h', habitat: 'WILD', diet: 'Meat & Carrion', isWildHabitat: true, isWildDiet: false },
  { id: 61, name: 'Crimson Finch', fact: 'One of the few finches that nests near crocs', habitat: 'Wetlands & Waterways', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 62, name: 'Currawong', fact: "Its name mimics its ringing curra-wong call", habitat: 'Bushland & Scrub', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 63, name: 'Tawny Frogmouth', fact: "Not an owl – it catches prey with its beak", habitat: 'Bushland & Scrub', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 64, name: 'Osprey', fact: 'Has reversible toes for gripping slippery fish', habitat: 'Coastal & Ocean', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 65, name: 'Rose-crowned Fruit-Dove', fact: "So well-camouflaged it's usually heard first", habitat: 'Rainforest', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 66, name: 'Masked Lapwing', fact: 'Has hidden spurs on its wings for combat', habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 67, name: 'Yellow-tailed Cockatoo', fact: 'Rips bark off trees to find hidden grubs', habitat: 'Bushland & Scrub', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 68, name: 'Superb Fruit-Dove', fact: "Male's purple crown glows in dappled light", habitat: 'Rainforest', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 69, name: 'Buff-banded Rail', fact: 'Sneaks through reeds almost never taking flight', habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 70, name: 'Australian Hobby', fact: 'Catches dragonflies and eats them on the wing', habitat: 'Outback & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 71, name: 'Catbird', fact: 'Named for its wailing cat-like call', habitat: 'Rainforest', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 72, name: 'Mistletoebird', fact: 'Spreads mistletoe by wiping seeds on branches', habitat: 'Rainforest', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 73, name: 'Pheasant Coucal', fact: 'Only Australian cuckoo that raises its own young', habitat: 'Rainforest', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 74, name: 'Egret', fact: 'Grows long lacy plumes just for breeding season', habitat: 'Rainforest', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 75, name: 'Boobook Owl', fact: "Australia's smallest owl calls its own name", habitat: 'Rainforest', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 76, name: 'Cockatiel', fact: 'Only cockatoo small enough to perch on grass', habitat: 'Bushland & Scrub', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 77, name: 'Scaly-breasted Lorikeet', fact: 'Almost invisible until it opens its red bill', habitat: 'Bushland & Scrub', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 78, name: 'Regent Honeyeater', fact: "So rare it's forgetting its own species' song", habitat: 'Bushland & Scrub', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 79, name: 'Noisy Miner', fact: 'Gangs up to mob birds ten times its size', habitat: 'Bushland & Scrub', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 80, name: 'Dollarbird', fact: 'Named for the silver coin shape in its wings', habitat: 'Bushland & Scrub', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 81, name: 'Grey Butcherbird', fact: 'Wedges prey in tree forks like a larder', habitat: 'Bushland & Scrub', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 82, name: 'Coot', fact: 'Builds a floating nest anchored to reeds', habitat: 'Wetlands & Waterways', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 83, name: 'Sahul Sunbird', fact: "Australia's only sunbird – tiny and iridescent", habitat: 'Wetlands & Waterways', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 84, name: 'Ibis', fact: "Revered in ancient Egypt, beloved as the Bin Chicken", habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 85, name: 'Jacana', fact: 'Walks on lily pads with enormous spread toes', habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 86, name: 'Curlew', fact: 'Its eerie wail carries a kilometre at night', habitat: 'Wetlands & Waterways', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 87, name: 'Chough', fact: 'Builds a mud bowl nest glued to a branch', habitat: 'Wetlands & Waterways', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 88, name: 'Pale-headed Rosella', fact: 'Head colour ranges from cream to bright yellow', habitat: 'Coastal & Ocean', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 89, name: 'Channel-billed Cuckoo', fact: "World's largest parasitic bird at 60cm long", habitat: 'Coastal & Ocean', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 90, name: 'Avocet', fact: 'Sweeps its upturned bill through shallow water', habitat: 'Coastal & Ocean', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 91, name: 'Fairy Martin', fact: 'Builds bottle-shaped mud nests under bridges', habitat: 'Coastal & Ocean', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 92, name: 'Booby', fact: 'Named by sailors for being too trusting', habitat: 'Coastal & Ocean', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 93, name: 'Frigatebird', fact: 'Pirates food from other seabirds in mid-air', habitat: 'Coastal & Ocean', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 94, name: 'Corella', fact: "Digs up roots and bulbs with its stubby bill", habitat: 'Outback & Grassland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 95, name: 'Paradise Parrot', fact: 'Last confirmed sighting was in 1927', habitat: 'Outback & Grassland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 96, name: 'Green Oriole', fact: 'Its song sounds like bubbling tropical water', habitat: 'Outback & Grassland', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 97, name: 'Apostlebird', fact: 'Named because flocks were said to number twelve', habitat: 'Outback & Grassland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 98, name: 'Bustard', fact: 'Australia\'s heaviest flying bird at up to 15kg', habitat: 'Outback & Grassland', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 99, name: 'Magpie', fact: 'Can recognise over 100 different human faces', habitat: 'Outback & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 100, name: 'Brush Turkey', fact: 'Builds a compost mound up to 4 metres wide', habitat: 'Outback & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
];
