// Bucket List: Australian Birds — Card Definitions
// Generated from CSV data

export const HABITATS = [
  'Rainforest',
  'Bushland & Scrub',
  'Wetlands & Waterways',
  'Coastal & Ocean',
  'Outback & Grassland',
];

export const DIETS = [
  'Seeds & Grain',
  'Nectar & Fruit',
  'Insects & Invertebrates',
  'Fish & Aquatic Prey',
  'Meat & Carrion',
];

export const HABITAT_COLORS = {
  'Rainforest': { gradient: '#1A4731-#2D6A4F', display: 'deep emerald' },
  'Bushland & Scrub': { gradient: '#7C5213-#A0692E', display: 'eucalyptus ochre' },
  'Wetlands & Waterways': { gradient: '#0F4C65-#1B6E8A', display: 'deep teal' },
  'Coastal & Ocean': { gradient: '#0C3264-#1E4DA0', display: 'ocean navy' },
  'Outback & Grassland': { gradient: '#8B3A0A-#B4541F', display: 'burnt terracotta' },
  'WILD': { gradient: '#4C1D95-#6D28D9', display: 'purple' },
};

export const DIET_COLORS = {
  'Seeds & Grain': '#D97706',
  'Nectar & Fruit': '#BE185D',
  'Insects & Invertebrates': '#047857',
  'Fish & Aquatic Prey': '#0369A1',
  'Meat & Carrion': '#B91C1C',
  'WILD': '#7C3AED',
};

// Icon filename mappings
export const ICON_MAP = {
  'Rainforest': 'category_rainforest.png',
  'Bushland & Scrub': 'category_scrub.png',
  'Wetlands & Waterways': 'category_wetlands.png',
  'Coastal & Ocean': 'category_ocean.png',
  'Outback & Grassland': 'category_outback.png',
  'WILD_HABITAT': 'category_wild.png',
  'Seeds & Grain': 'category_seeds.png',
  'Nectar & Fruit': 'category_fruit.png',
  'Insects & Invertebrates': 'category_insects.png',
  'Fish & Aquatic Prey': 'category_fish.png',
  'Meat & Carrion': 'category_carnivore.png',
  'WILD_DIET': 'category_wild.png',
};

export const AUSTRALIAN_BIRDS = [
  { id: 1, name: 'King Parrot', fact: 'Males take 3 years to turn fully red', habitat: 'Rainforest', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 2, name: 'Double-eyed Fig-Parrot', fact: "Australia's smallest parrot at just 14cm", habitat: 'Rainforest', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 3, name: 'Wompoo Pigeon', fact: 'Can swallow whole fruits bigger than its head', habitat: 'Rainforest', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 4, name: 'Regent Bowerbird', fact: "Mixes its own paint to decorate its bower", habitat: 'Rainforest', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 5, name: 'Noisy Pitta', fact: "Smashes snails on a favourite rock 'anvil'", habitat: 'Rainforest', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 6, name: 'Rufous Fantail', fact: 'Fans its tail to startle insects into flight', habitat: 'Rainforest', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 7, name: 'Azure Kingfisher', fact: 'Beats fish against a branch before eating', habitat: 'Rainforest', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 8, name: 'Green Pygmy Goose', fact: "Not a goose at all – it's a tiny perching duck", habitat: 'Rainforest', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 9, name: 'Grey Goshawk', fact: "Australia's only pure white bird of prey", habitat: 'Rainforest', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 10, name: 'Rufous Owl', fact: 'Can catch possums and sugar gliders mid-air', habitat: 'Rainforest', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 11, name: 'Eastern Crimson Rosella', fact: "Some populations are yellow, not crimson", habitat: 'Bushland & Scrub', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 12, name: 'Sulphur-crested Cockatoo', fact: 'Can live over 80 years in captivity', habitat: 'Bushland & Scrub', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 13, name: 'Scarlet Honeyeater', fact: 'Weighs less than two teaspoons of sugar', habitat: 'Bushland & Scrub', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 14, name: 'Rainbow Lorikeet', fact: 'Has a brush-tipped tongue for licking nectar', habitat: 'Bushland & Scrub', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 15, name: 'Splendid Fairywren', fact: 'Males bring petals to females as courtship gifts', habitat: 'Bushland & Scrub', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 16, name: 'Red-capped Robin', fact: 'Can spot a moving insect from 40 metres away', habitat: 'Bushland & Scrub', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 17, name: 'Laughing Kookaburra', fact: 'Its laugh marks territory at dawn and dusk', habitat: 'Bushland & Scrub', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 18, name: 'Sacred Kingfisher', fact: 'Nests inside termite mounds in tree trunks', habitat: 'Bushland & Scrub', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 19, name: 'Powerful Owl', fact: "Roosts all day clutching last night's catch", habitat: 'Bushland & Scrub', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 20, name: 'Barking Owl', fact: 'Screaming call once mistaken for a woman', habitat: 'Bushland & Scrub', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 21, name: 'Black Swan', fact: "Once thought impossible – now WA's emblem", habitat: 'Wetlands & Waterways', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 22, name: 'Magpie Goose', fact: 'A living fossil with half-webbed feet', habitat: 'Wetlands & Waterways', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 23, name: 'Spinebill', fact: 'Can hover like a hummingbird at flowers', habitat: 'Wetlands & Waterways', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 24, name: "Lewin's Honeyeater", fact: 'Named after a convict ship artist in 1801', habitat: 'Wetlands & Waterways', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 25, name: 'Rainbow Bee-eater', fact: 'Rubs bee stings off on a branch before eating', habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 26, name: 'Royal Spoonbill', fact: 'Sweeps its spoon-shaped bill side to side', habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 27, name: 'Nankeen Night Heron', fact: "Hunts by moonlight, sleeps hidden by day", habitat: 'Wetlands & Waterways', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 28, name: 'Australian Pelican', fact: 'Has the longest bill of any living bird', habitat: 'Wetlands & Waterways', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 29, name: 'Swamp Harrier', fact: 'Passes food to its mate mid-flight', habitat: 'Wetlands & Waterways', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 30, name: 'White-faced Heron', fact: 'Vibrates its foot underwater to lure prey', habitat: 'Wetlands & Waterways', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 31, name: 'Crested Pigeon', fact: 'Its wings make a whistling alarm when it takes off', habitat: 'Coastal & Ocean', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 32, name: 'Bush Stone-curlew', fact: 'Freezes statue-still when threatened', habitat: 'Coastal & Ocean', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 33, name: 'Noisy Friarbird', fact: "Bald black head earned it the name 'leatherhead'", habitat: 'Coastal & Ocean', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 34, name: 'Little Wattlebird', fact: "Named 'little' but is actually 30cm long", habitat: 'Coastal & Ocean', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 35, name: 'Sooty Oystercatcher', fact: 'Uses its bill like a chisel on rock oysters', habitat: 'Coastal & Ocean', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 36, name: 'Pied Oystercatcher', fact: 'Chicks can swim within hours of hatching', habitat: 'Coastal & Ocean', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 37, name: 'White-bellied Sea Eagle', fact: 'Mates lock talons and cartwheel through the sky', habitat: 'Coastal & Ocean', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 38, name: 'Australasian Gannet', fact: 'Plunge-dives from 30 metres at 100 km/h', habitat: 'Coastal & Ocean', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 39, name: 'Brahminy Kite', fact: 'Sacred in Hindu mythology as Vishnu\'s bird', habitat: 'Coastal & Ocean', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 40, name: 'Pacific Gull', fact: 'Drops shellfish from height to crack them open', habitat: 'Coastal & Ocean', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 41, name: 'Gouldian Finch', fact: "Comes in red, black, or yellow-headed forms", habitat: 'Outback & Grassland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 42, name: 'Princess Parrot', fact: 'May vanish from an area for 20 years', habitat: 'Outback & Grassland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 43, name: 'Crimson Chat', fact: 'Fakes a broken wing to lure predators away', habitat: 'Outback & Grassland', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 44, name: 'Pied Honeyeater', fact: 'Performs a spectacular spiralling song flight', habitat: 'Outback & Grassland', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 45, name: 'Nankeen Kestrel', fact: 'Hovers perfectly still in wind like a drone', habitat: 'Outback & Grassland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 46, name: 'Budgerigar', fact: "Wild flocks can number over 10,000 birds", habitat: 'Outback & Grassland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 47, name: 'Brolga', fact: 'Famous for its elaborate courtship dance', habitat: 'Outback & Grassland', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 48, name: 'Black-necked Stork', fact: "Australia's only stork – often called Jabiru", habitat: 'Outback & Grassland', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 49, name: 'Wedge-tailed Eagle', fact: '2.3m wingspan – can soar for hours unseen', habitat: 'Outback & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 50, name: 'Crow', fact: 'Can solve multi-step puzzles for food', habitat: 'Outback & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 51, name: 'Southern Cassowary', fact: 'Its kick can be lethal to humans', habitat: 'Rainforest', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 52, name: 'Superb Lyrebird', fact: "Can mimic chainsaws, cameras, and car alarms", habitat: 'Bushland & Scrub', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 53, name: 'Purple Swamphen', fact: 'Holds food in one foot like a hand to eat', habitat: 'Wetlands & Waterways', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 54, name: 'Little Penguin', fact: "World's smallest penguin at just 33cm tall", habitat: 'Coastal & Ocean', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 55, name: 'Emu', fact: 'Dad sits on the eggs and raises chicks alone', habitat: 'Outback & Grassland', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 56, name: 'Galah', fact: "Aussie slang for a fool is named after it", habitat: 'WILD', diet: 'Seeds & Grain', isWildHabitat: true, isWildDiet: false },
  { id: 57, name: 'Figbird', fact: 'Males have bright red bare skin around eyes', habitat: 'WILD', diet: 'Nectar & Fruit', isWildHabitat: true, isWildDiet: false },
  { id: 58, name: 'Satin Bowerbird', fact: 'Obsessively collects anything blue for its bower', habitat: 'WILD', diet: 'Insects & Invertebrates', isWildHabitat: true, isWildDiet: false },
  { id: 59, name: 'Darter', fact: 'Swims with only its snake-like neck showing', habitat: 'WILD', diet: 'Fish & Aquatic Prey', isWildHabitat: true, isWildDiet: false },
  { id: 60, name: 'Peregrine Falcon', fact: 'Fastest animal on Earth at 390 km/h', habitat: 'WILD', diet: 'Meat & Carrion', isWildHabitat: true, isWildDiet: false },
  { id: 61, name: 'Crimson Finch', fact: 'One of the few finches that nests near crocs', habitat: 'Wetlands & Waterways', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 62, name: 'Currawong', fact: "Its name mimics its ringing curra-wong call", habitat: 'Bushland & Scrub', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 63, name: 'Tawny Frogmouth', fact: "Not an owl – it catches prey with its beak", habitat: 'Bushland & Scrub', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 64, name: 'Osprey', fact: 'Has reversible toes for gripping slippery fish', habitat: 'Coastal & Ocean', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 65, name: 'Rose-crowned Fruit-Dove', fact: "So well-camouflaged it's usually heard first", habitat: 'Rainforest', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 66, name: 'Masked Lapwing', fact: 'Has hidden spurs on its wings for combat', habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 67, name: 'Yellow-tailed Cockatoo', fact: 'Rips bark off trees to find hidden grubs', habitat: 'Bushland & Scrub', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 68, name: 'Superb Fruit-Dove', fact: "Male's purple crown glows in dappled light", habitat: 'Rainforest', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 69, name: 'Buff-banded Rail', fact: 'Sneaks through reeds almost never taking flight', habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 70, name: 'Australian Hobby', fact: 'Catches dragonflies and eats them on the wing', habitat: 'Outback & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 71, name: 'Catbird', fact: 'Named for its wailing cat-like call', habitat: 'Rainforest', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 72, name: 'Mistletoebird', fact: 'Spreads mistletoe by wiping seeds on branches', habitat: 'Rainforest', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 73, name: 'Pheasant Coucal', fact: 'Only Australian cuckoo that raises its own young', habitat: 'Rainforest', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 74, name: 'Egret', fact: 'Grows long lacy plumes just for breeding season', habitat: 'Rainforest', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 75, name: 'Boobook Owl', fact: "Australia's smallest owl calls its own name", habitat: 'Rainforest', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 76, name: 'Cockatiel', fact: 'Only cockatoo small enough to perch on grass', habitat: 'Bushland & Scrub', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 77, name: 'Scaly-breasted Lorikeet', fact: 'Almost invisible until it opens its red bill', habitat: 'Bushland & Scrub', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 78, name: 'Regent Honeyeater', fact: "So rare it's forgetting its own species' song", habitat: 'Bushland & Scrub', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 79, name: 'Noisy Miner', fact: 'Gangs up to mob birds ten times its size', habitat: 'Bushland & Scrub', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 80, name: 'Dollarbird', fact: 'Named for the silver coin shape in its wings', habitat: 'Bushland & Scrub', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 81, name: 'Grey Butcherbird', fact: 'Wedges prey in tree forks like a larder', habitat: 'Bushland & Scrub', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 82, name: 'Coot', fact: 'Builds a floating nest anchored to reeds', habitat: 'Wetlands & Waterways', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 83, name: 'Sahul Sunbird', fact: "Australia's only sunbird – tiny and iridescent", habitat: 'Wetlands & Waterways', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 84, name: 'Ibis', fact: "Revered in ancient Egypt, beloved as the Bin Chicken", habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 85, name: 'Jacana', fact: 'Walks on lily pads with enormous spread toes', habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 86, name: 'Curlew', fact: 'Its eerie wail carries a kilometre at night', habitat: 'Wetlands & Waterways', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 87, name: 'Chough', fact: 'Builds a mud bowl nest glued to a branch', habitat: 'Wetlands & Waterways', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 88, name: 'Pale-headed Rosella', fact: 'Head colour ranges from cream to bright yellow', habitat: 'Coastal & Ocean', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 89, name: 'Channel-billed Cuckoo', fact: "World's largest parasitic bird at 60cm long", habitat: 'Coastal & Ocean', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 90, name: 'Avocet', fact: 'Sweeps its upturned bill through shallow water', habitat: 'Coastal & Ocean', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 91, name: 'Fairy Martin', fact: 'Builds bottle-shaped mud nests under bridges', habitat: 'Coastal & Ocean', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 92, name: 'Booby', fact: 'Named by sailors for being too trusting', habitat: 'Coastal & Ocean', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 93, name: 'Frigatebird', fact: 'Pirates food from other seabirds in mid-air', habitat: 'Coastal & Ocean', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 94, name: 'Corella', fact: "Digs up roots and bulbs with its stubby bill", habitat: 'Outback & Grassland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 95, name: 'Paradise Parrot', fact: 'Last confirmed sighting was in 1927', habitat: 'Outback & Grassland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 96, name: 'Green Oriole', fact: 'Its song sounds like bubbling tropical water', habitat: 'Outback & Grassland', diet: 'Nectar & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 97, name: 'Apostlebird', fact: 'Named because flocks were said to number twelve', habitat: 'Outback & Grassland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 98, name: 'Bustard', fact: 'Australia\'s heaviest flying bird at up to 15kg', habitat: 'Outback & Grassland', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 99, name: 'Magpie', fact: 'Can recognise over 100 different human faces', habitat: 'Outback & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 100, name: 'Brush Turkey', fact: 'Builds a compost mound up to 4 metres wide', habitat: 'Outback & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
];

export const BRITISH_BIRDS = [
  { id: 1, name: 'House Sparrow', fact: 'Chirpy social birds found in every garden and city. Britain\'s most familiar garden companion.', habitat: 'Garden & Urban', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 2, name: 'Woodpigeon', fact: 'Large plump pigeon with distinctive cooing call. Famous for raiding gardens and feeding on grain.', habitat: 'Garden & Urban', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 3, name: 'Blackbird', fact: 'Male is glossy black with bright orange-yellow beak. Famous for melodious evening song.', habitat: 'Garden & Urban', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 4, name: 'Song Thrush', fact: 'Spotted breast and warm brown back. Repeats song phrases three times from high perches.', habitat: 'Garden & Urban', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 5, name: 'Robin', fact: 'Britain\'s national bird with iconic red breast. Confiding garden visitor symbol of Christmas.', habitat: 'Garden & Urban', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 6, name: 'Blue Tit', fact: 'Tiny ball of blue and yellow plumage. Acrobatic feeder on garden plants and feeders.', habitat: 'Garden & Urban', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 7, name: 'Little Grebe', fact: 'Tiny diving duck of urban park lakes. Shy bird that disappears underwater when alarmed.', habitat: 'Garden & Urban', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 8, name: 'Great Crested Grebe', fact: 'Elegant waterbird with striking crest and black ear tufts. Famous for elaborate courtship displays.', habitat: 'Garden & Urban', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 9, name: 'Magpie', fact: 'Boldly patterned black and white with long tail. Intelligent chattering and inquisitive bird.', habitat: 'Garden & Urban', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 10, name: 'Sparrowhawk', fact: 'Sleek blue-grey raptor that hunts garden birds with lightning speed and agility.', habitat: 'Garden & Urban', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 11, name: 'Chaffinch', fact: 'Colorful finch with rusty face and blue-grey head. Bouncing flight and cheerful song.', habitat: 'Woodland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 12, name: 'Jay', fact: 'Striking colourful woodland bird with crest and loud raucous calls. Eats acorns and buries them.', habitat: 'Woodland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 13, name: 'Mistle Thrush', fact: 'Large spotted thrush that feeds on mistletoe berries and rowan berries in winter.', habitat: 'Woodland', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 14, name: 'Bullfinch', fact: 'Stocky finch with black cap and brilliant rose-red breast in males. Visits fruit trees.', habitat: 'Woodland', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 15, name: 'Great Spotted Woodpecker', fact: 'Black and white with dramatic red undertail. Distinctive loud drumming on dead wood.', habitat: 'Woodland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 16, name: 'Wren', fact: 'Tiny brown bird with loud explosive song. Hunts insects in dense cover and shrubbery.', habitat: 'Woodland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 17, name: 'Kingfisher', fact: 'Brilliant turquoise and orange jewel of rivers and streams. Hunts small fish with precision dives.', habitat: 'Woodland', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 18, name: 'Dipper', fact: 'Small dark bird that walks underwater hunting for aquatic invertebrates in mountain streams.', habitat: 'Woodland', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 19, name: 'Tawny Owl', fact: 'Most common owl with dark reddish plumage and eerie hooting call. Hunts small mammals at night.', habitat: 'Woodland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 20, name: 'Goshawk', fact: 'Powerful forest raptor that hunts large birds and rabbits with incredible agility through trees.', habitat: 'Woodland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 21, name: 'Skylark', fact: 'Bird of open grassland famous for soaring song flight high in the sky at dawn.', habitat: 'Farmland & Grassland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 22, name: 'Yellowhammer', fact: 'Golden-headed bunting with rich song. Declining farmland bird that nests in hedgerows.', habitat: 'Farmland & Grassland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 23, name: 'Fieldfare', fact: 'Large spotted thrush that visits fields and hedgerows in winter to feed on berries.', habitat: 'Farmland & Grassland', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 24, name: 'Redwing', fact: 'Smaller cousin of Fieldfare with distinctive red underwing stripe. Winter visitor to hedgerows.', habitat: 'Farmland & Grassland', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 25, name: 'Lapwing', fact: 'Distinctive black and white plover with long crest. Tumbling display flight over fields.', habitat: 'Farmland & Grassland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 26, name: 'Starling', fact: 'Glossy black with white spots. Forms spectacular murmurations of thousands at dusk.', habitat: 'Farmland & Grassland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 27, name: 'Little Egret', fact: 'Delicate white heron with black legs and yellow feet. Now common on British wetlands.', habitat: 'Farmland & Grassland', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 28, name: 'Grey Wagtail', fact: 'Elegant grey and yellow wagtail that hunts flies over farm streams and ditches.', habitat: 'Farmland & Grassland', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 29, name: 'Barn Owl', fact: 'Ghostly white heart-faced owl that hunts voles over farmland at dusk and dawn.', habitat: 'Farmland & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 30, name: 'Buzzard', fact: 'Common broad-winged raptor seen soaring over fields. Hunts small mammals and rabbits.', habitat: 'Farmland & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 31, name: 'Canada Goose', fact: 'Large dark goose with black neck and white chinstrap. Now common on British lakes.', habitat: 'Wetlands & Waterways', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 32, name: 'Mute Swan', fact: 'Iconic pure white swan with orange bill. Graceful on water but aggressive in defense.', habitat: 'Wetlands & Waterways', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 33, name: 'Mallard', fact: 'Commonest duck with green-headed drake and brown female. Found on every pond and river.', habitat: 'Wetlands & Waterways', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 34, name: 'Moorhen', fact: 'Black waterbird with red and yellow shield on face. Walks at water\'s edge searching for food.', habitat: 'Wetlands & Waterways', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 35, name: 'Reed Warbler', fact: 'Streaky brown warbler that nests in reed beds over water. Beautiful flowing song.', habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 36, name: 'Sedge Warbler', fact: 'Paler streaky warbler with bold eyebrow stripe. Loud song from low perches in rushes.', habitat: 'Wetlands & Waterways', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 37, name: 'Grey Heron', fact: 'Tall elegant grey heron standing motionless waiting for fish. Patient and deadly hunter.', habitat: 'Wetlands & Waterways', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 38, name: 'Cormorant', fact: 'Dark waterbird with long neck and crooked bill. Dives deep for fish in lakes and rivers.', habitat: 'Wetlands & Waterways', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 39, name: 'Marsh Harrier', fact: 'Rare elegant raptor that hunts over wetlands and reed beds. Female is brown male pale.', habitat: 'Wetlands & Waterways', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 40, name: 'Hen Harrier', fact: 'Sleek raptor that hunts low over moorland and grassland with buoyant flight.', habitat: 'Wetlands & Waterways', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 41, name: 'Linnet', fact: 'Delicate finch with red face and breast in males. Sings twittering song from gorse bushes.', habitat: 'Coastal & Marine', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 42, name: 'Snow Bunting', fact: 'White and buff bunting that arrives from Arctic in winter. Males very pale almost white.', habitat: 'Coastal & Marine', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 43, name: 'Stonechat', fact: 'Tiny colorful chat with black head and orange breast. Perches on gorse and heather.', habitat: 'Coastal & Marine', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 44, name: 'Common Redstart', fact: 'Beautiful male with grey back and orange-red breast. Migrants passing through coasts.', habitat: 'Coastal & Marine', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 45, name: 'Oystercatcher', fact: 'Striking pied wading bird with long orange bill. Loud piping calls on rocky shores.', habitat: 'Coastal & Marine', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 46, name: 'Ringed Plover', fact: 'Small pale plover with bold black and white head pattern. Nests on shingle beaches.', habitat: 'Coastal & Marine', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 47, name: 'Gannet', fact: 'Brilliant white seabird with black wing tips and yellow head. Plunges spectacularly for fish.', habitat: 'Coastal & Marine', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 48, name: 'Arctic Tern', fact: 'Elegant tern with grey and white plumage and red bill. Makes longest migration of any bird.', habitat: 'Coastal & Marine', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 49, name: 'Herring Gull', fact: 'Large white gull with grey back and yellow bill. Familiar sound of seaside resorts.', habitat: 'Coastal & Marine', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 50, name: 'Greater Black-backed Gull', fact: 'Massive black-backed gull that takes small birds and rabbits. Largest gull in Britain.', habitat: 'Coastal & Marine', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 51, name: 'Ring-necked Parakeet', fact: 'Emerald green parrot with ring marking. Now established in London parks escaped from captivity.', habitat: 'Garden & Urban', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 52, name: 'Green Woodpecker', fact: 'Large green woodpecker with loud laughing call. Eats ants from ground and tree bark.', habitat: 'Woodland', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 53, name: 'Curlew', fact: 'Large wading bird with long decurved bill and haunting call. Declining symbol of wildness.', habitat: 'Farmland & Grassland', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 54, name: 'Bittern', fact: 'Secretive reed bed specialist famous for booming call at night. Once nearly extinct in Britain.', habitat: 'Wetlands & Waterways', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 55, name: 'Puffin', fact: 'Adorable seabird with colourful bill and round face. Britain\'s most beloved seabird icon.', habitat: 'Coastal & Marine', diet: 'WILD', isWildHabitat: false, isWildDiet: true },
  { id: 56, name: 'Goldfinch', fact: 'Beautiful finch with red face and striking black and gold wings. Visits teasel and thistle seedheads.', habitat: 'WILD', diet: 'Seeds & Grain', isWildHabitat: true, isWildDiet: false },
  { id: 57, name: 'Waxwing', fact: 'Exotic looking starling-sized bird with crest. Winter visitor when berry crops fail in northern forests.', habitat: 'WILD', diet: 'Berries & Fruit', isWildHabitat: true, isWildDiet: false },
  { id: 58, name: 'Swallow', fact: 'Elegant blue-black swallow with red face. Summer visitor skimming insects from air and water.', habitat: 'WILD', diet: 'Insects & Invertebrates', isWildHabitat: true, isWildDiet: false },
  { id: 59, name: 'Osprey', fact: 'Spectacular fish-eating raptor with white underparts and bold eye stripe. Makes dramatic plunge dives.', habitat: 'WILD', diet: 'Fish & Aquatic Prey', isWildHabitat: true, isWildDiet: false },
  { id: 60, name: 'Red Kite', fact: 'Impressive reddish-brown raptor with forked tail. Britain\'s greatest conservation success story.', habitat: 'WILD', diet: 'Meat & Carrion', isWildHabitat: true, isWildDiet: false },
  { id: 61, name: 'Great Tit', fact: 'Striking bird with black and white head and white cheeks. Loud clear song and acrobatic feeder.', habitat: 'Garden & Urban', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 62, name: 'Long-tailed Tit', fact: 'Tiny fluffy ball with very long tail. Visits gardens in small chattering flocks in winter.', habitat: 'Garden & Urban', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 63, name: 'Dunnock', fact: 'Shy brownish bird with blue-grey head. Hunts insects under hedges and shrubs.', habitat: 'Garden & Urban', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 64, name: 'House Martin', fact: 'White-rumped swallow that builds mud nests under eaves. Aerial insect hunter.', habitat: 'Garden & Urban', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 65, name: 'Feral Pigeon', fact: 'Descendant of Rock Doves now living in cities everywhere. Comes in wild blue or pied colors.', habitat: 'Garden & Urban', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 66, name: 'Swift', fact: 'Screaming fast swallow that catches insects high in air. Never lands except at nest.', habitat: 'Garden & Urban', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 67, name: 'Jackdaw', fact: 'Small crow with pale nape and eye. Forms flocks and nests in colonies on cliffs and buildings.', habitat: 'Garden & Urban', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 68, name: 'Carrion Crow', fact: 'All-black crow that hunts alone or in pairs. Less social than Rooks but very intelligent.', habitat: 'Garden & Urban', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 69, name: 'Nuthatch', fact: 'Acrobatic blue-grey bird that walks headfirst down trees. Wedges seeds in bark crevices.', habitat: 'Woodland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 70, name: 'Coal Tit', fact: 'Small tit with distinctive black head and two white neck patches. Hides seeds throughout woodland.', habitat: 'Woodland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 71, name: 'Siskin', fact: 'Small elegant finch with yellow and black markings. Acrobatic feeder on alder and birch seeds.', habitat: 'Woodland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 72, name: 'Crossbill', fact: 'Unique finch with crossed bill for extracting conifer seeds. Nomadic following seed crops.', habitat: 'Woodland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 73, name: 'Treecreeper', fact: 'Tiny brown bird that spirals up tree trunks hunting insects in bark. Elusive and hard to spot.', habitat: 'Woodland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 74, name: 'Willow Warbler', fact: 'Tiny olive-green warbler that migrates through Britain in spring and autumn. Fluty song.', habitat: 'Woodland', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 75, name: 'Chiffchaff', fact: 'Small warbler with name reflected in song. First returning migrant herald of spring.', habitat: 'Woodland', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 76, name: 'Nightingale', fact: 'Legendary singer hidden in dense cover. One of finest songsters but rarely seen.', habitat: 'Woodland', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 77, name: 'Blackcap', fact: 'Small grey warbler with black cap in males. Beautiful flute-like song in spring.', habitat: 'Woodland', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 78, name: 'Pied Flycatcher', fact: 'Smart black and white warbler that hunts insects in the air. Summer visitor to woodlands.', habitat: 'Woodland', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 79, name: 'Pheasant', fact: 'Colorful game bird with long tail. Male iridescent with red face markings.', habitat: 'Farmland & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 80, name: 'Grey Partridge', fact: 'Plump game bird of grassland and cereal crops. Declining due to modern farming practices.', habitat: 'Farmland & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 81, name: 'Red Grouse', fact: 'Deep red-brown grouse that lives on upland heather moors. Famous for driving out of cover.', habitat: 'Farmland & Grassland', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 82, name: 'Pied Wagtail', fact: 'Elegant black and white wagtail with constant tail-bobbing. Hunts insects over water.', habitat: 'Farmland & Grassland', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 83, name: 'Rook', fact: 'Black crow with bare white face patch and shaggy leg feathers. Nests in colonies called rookeries.', habitat: 'Farmland & Grassland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 84, name: 'Golden Plover', fact: 'Golden-speckled plover of upland grassland. Forms huge winter flocks with other plovers.', habitat: 'Farmland & Grassland', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
  { id: 85, name: 'Kestrel', fact: 'Smallest falcon that hovers above fields hunting voles. Rufous back and long black tail.', habitat: 'Farmland & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 86, name: 'Short-eared Owl', fact: 'Long-winged owl that hunts low over open ground in daylight. Yellow eyes and fierce expression.', habitat: 'Farmland & Grassland', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 87, name: 'Coot', fact: 'Black water bird with distinctive white frontal shield on face. Aggressive territorial bird.', habitat: 'Wetlands & Waterways', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 88, name: 'Wigeon', fact: 'Smart diving duck with chestnut head and cream forehead in males. Grazes on aquatic plants.', habitat: 'Wetlands & Waterways', diet: 'Berries & Fruit', isWildHabitat: false, isWildDiet: false },
  { id: 89, name: 'Teal', fact: 'Tiny dabbling duck with green head and cream breast in males. Commonest small duck.', habitat: 'Wetlands & Waterways', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 90, name: 'Bearded Tit', fact: 'Striking reed bed specialist with long tail and black moustache in males. Beautiful orange plumage.', habitat: 'Wetlands & Waterways', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 91, name: 'Water Rail', fact: 'Secretive slate-blue rail that hides in reeds. Loud grunting calls betray its presence.', habitat: 'Wetlands & Waterways', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 92, name: 'Snipe', fact: 'Camouflaged wading bird with long bill that probes for worms in mud. Zig-zag escape flight.', habitat: 'Wetlands & Waterways', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 93, name: 'Tufted Duck', fact: 'Black and white duck with distinctive tuft at back of head. Male glossy black white-sided.', habitat: 'Wetlands & Waterways', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 94, name: 'Greylag Goose', fact: 'Large grey-brown goose ancestor of domestic geese. Loud honking calls and strong fliers.', habitat: 'Wetlands & Waterways', diet: 'Seeds & Grain', isWildHabitat: false, isWildDiet: false },
  { id: 95, name: 'Guillemot', fact: 'Black and white auk with long thin bill. Nests in huge colonies on sea cliffs.', habitat: 'Coastal & Marine', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 96, name: 'Razorbill', fact: 'Dumpy auk with short thick bill with white line. Takes flying fish with impressive diving.', habitat: 'Coastal & Marine', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 97, name: 'White-tailed Eagle', fact: 'Massive golden eagle reintroduced to Scotland. Hunts fish from lochs with awesome power.', habitat: 'Coastal & Marine', diet: 'Fish & Aquatic Prey', isWildHabitat: false, isWildDiet: false },
  { id: 98, name: 'Merlin', fact: 'Tiny fierce falcon that hunts small birds at speed. Male slate-blue female brown.', habitat: 'Coastal & Marine', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 99, name: 'Golden Eagle', fact: 'Majestic mountain eagle with golden crown. Rarest and most powerful British raptor.', habitat: 'Coastal & Marine', diet: 'Meat & Carrion', isWildHabitat: false, isWildDiet: false },
  { id: 100, name: 'Chough', fact: 'Glossy black crow with red legs and bill. Rare bird of rocky cliffs in West Wales.', habitat: 'Coastal & Marine', diet: 'Insects & Invertebrates', isWildHabitat: false, isWildDiet: false },
];

export const LONDON_TRAVEL = [
  { id: 1, name: "Simpson's in the Strand", fact: 'Victorian dining rooms serving roasts since 1828', location: 'Historic Landmarks', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 2, name: 'Ye Olde Cheshire Cheese', fact: 'Historic pub rebuilt after the Great Fire of 1666', location: 'Historic Landmarks', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 3, name: 'The Cenotaph', fact: "Nation's war memorial — stop, remember, move on", location: 'Historic Landmarks', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 4, name: 'Leadenhall Market', fact: 'Ornate Victorian arcade that inspired Diagon Alley', location: 'Historic Landmarks', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 5, name: 'Covent Garden Piazza', fact: 'Grand piazza with street performers since 1654', location: 'Historic Landmarks', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 6, name: "Platform 9¾ King's Cross", fact: "Harry Potter's vanishing platform photo spot", location: 'Historic Landmarks', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 7, name: 'The City of London', fact: 'Ancient financial district with medieval street plan', location: 'Historic Landmarks', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 8, name: 'Southwark', fact: 'Historic borough with Shakespeare and coaching inns', location: 'Historic Landmarks', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 9, name: 'Abbey Road Crossing', fact: "The world's most famous zebra crossing since 1969", location: 'Historic Landmarks', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 10, name: 'Westminster Abbey Gardens', fact: '900-year-old gardens hidden behind the Abbey', location: 'Historic Landmarks', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 11, name: 'Parliament Square Gardens', fact: 'Statues of world leaders facing Parliament', location: 'Historic Landmarks', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 12, name: 'Highgate Cemetery', fact: 'Victorian gothic necropolis — Karl Marx rests here', location: 'Historic Landmarks', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 13, name: 'Tower Bridge Walkway', fact: 'Glass-floor walkway 42 metres above the Thames', location: 'Historic Landmarks', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 14, name: 'Thames Path Somerset House', fact: 'Riverside walk past elegant 18th-century palace', location: 'Historic Landmarks', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 15, name: "Dennis Severs' House", fact: '18th-century time capsule in Spitalfields', location: 'Historic Landmarks', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 16, name: 'National Gallery Café', fact: 'Fine dining beneath Trafalgar Square masterpieces', location: 'Museums & Galleries', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 17, name: 'Dishoom Shoreditch', fact: 'Bombay-style café in a former railway goods yard', location: 'Museums & Galleries', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 18, name: "God's Own Junkyard", fact: 'Blazing neon art wonderland in Walthamstow', location: 'Museums & Galleries', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 19, name: 'Camden Lock Museum', fact: 'Eclectic market meets art installations by the canal', location: 'Museums & Galleries', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 20, name: 'Old Spitalfields Market', fact: 'Victorian market hall hosting art and antique fairs', location: 'Museums & Galleries', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 21, name: 'South Kensington', fact: 'Museum mile with three world-class institutions', location: 'Museums & Galleries', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 22, name: 'Bloomsbury', fact: 'Literary district home to the British Museum', location: 'Museums & Galleries', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 23, name: 'Leake Street Arches', fact: 'Legal graffiti tunnel — the walls change daily', location: 'Museums & Galleries', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 24, name: 'British Museum Great Court', fact: 'Two million years of history under a glass roof', location: 'Museums & Galleries', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 25, name: 'V&A Garden Courtyard', fact: 'Tranquil courtyard oasis in the design museum', location: 'Museums & Galleries', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 26, name: 'Tate Modern Bankside', fact: "Power station turned the world's favourite gallery", location: 'Museums & Galleries', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 27, name: "Butler's Wharf", fact: 'Converted Victorian wharves housing design museums', location: 'Museums & Galleries', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 28, name: 'Windsor Castle Tea Room', fact: "Afternoon tea in the world's oldest occupied castle", location: 'Royal Palaces', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 29, name: 'The Orangery', fact: 'Elegant afternoon tea in Kensington Palace gardens', location: 'Royal Palaces', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 30, name: 'The Churchill Arms', fact: 'Kensington pub draped in flowers and Thai food', location: 'Royal Palaces', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 31, name: 'Tower of London Market', fact: 'Medieval fortress hosting weekend artisan markets', location: 'Royal Palaces', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 32, name: 'Borough Market at the Shard', fact: "1,000-year-old market in a skyscraper's shadow", location: 'Royal Palaces', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 33, name: 'Hampton Court Village', fact: "Tudor village surrounding Henry VIII's palace", location: 'Royal Palaces', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 34, name: 'Kensington High Street', fact: 'Upscale shopping near Kensington Palace', location: 'Royal Palaces', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 35, name: 'Buckingham Palace Gardens', fact: '39 acres of private gardens behind the Palace', location: 'Royal Palaces', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 36, name: "St James's Park", fact: "Royal park with pelicans and Palace views", location: 'Royal Palaces', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 37, name: 'Little Venice Narrowboats', fact: 'Colourful canal boats at a pretty waterway junction', location: 'Royal Palaces', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 38, name: 'Thames Royal Pageant Route', fact: 'Royal river route past towers and palaces', location: 'Royal Palaces', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 39, name: 'Greenwich Observatory', fact: 'Where time begins — home of the Prime Meridian', location: 'Royal Palaces', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 40, name: 'Royal Albert Hall', fact: 'Victorian concert hall hosting 390 shows a year', location: 'Theatres & Entertainment', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 41, name: "Ronnie Scott's Jazz Club", fact: 'Legendary Soho jazz club since 1959', location: 'Theatres & Entertainment', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 42, name: "The Shard's Toilets", fact: "London's highest loo — a view worth queueing for", location: 'Theatres & Entertainment', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 43, name: "Shakespeare's Globe Shop", fact: 'Tudor theatre with riverside gift market', location: 'Theatres & Entertainment', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 44, name: 'Brixton Market Venues', fact: 'Vibrant market with live music and comedy clubs', location: 'Theatres & Entertainment', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 45, name: 'West End Theatreland', fact: "World's greatest concentration of theatres", location: 'Theatres & Entertainment', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 46, name: 'Shoreditch Entertainment', fact: 'Trendy bars, comedy, and live music after dark', location: 'Theatres & Entertainment', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 47, name: "Regent's Park Theatre", fact: 'Open-air Shakespeare under the summer stars', location: 'Theatres & Entertainment', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 48, name: 'Holland Park Opera', fact: 'Opera in a romantic woodland setting', location: 'Theatres & Entertainment', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 49, name: 'National Theatre Terrace', fact: 'Brutalist icon with free foyer performances', location: 'Theatres & Entertainment', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 50, name: "Gabriel's Wharf", fact: 'Creative riverside hub with street performances', location: 'Theatres & Entertainment', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 51, name: 'Duck & Waffle', fact: '24-hour restaurant on the 40th floor', location: 'Viewpoints', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 52, name: 'Aqua Shard', fact: 'Fine dining with floor-to-ceiling London panoramas', location: 'Viewpoints', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 53, name: 'The Shard Viewing Platform', fact: "Western Europe's tallest building — 72 floors up", location: 'Viewpoints', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 54, name: 'Greenwich Market Vista', fact: 'Bustling market with Canary Wharf tower views', location: 'Viewpoints', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 55, name: 'Notting Hill Overlook', fact: "Pastel houses climbing London's most colourful hill", location: 'Viewpoints', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 56, name: 'Hampstead Heath', fact: "Wild hilltop heath with London's best skyline view", location: 'Viewpoints', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 57, name: 'Sky Garden Terraces', fact: "London's highest garden — free but book ahead", location: 'Viewpoints', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 58, name: 'Primrose Hill', fact: 'The hilltop where all of London stretches before you', location: 'Viewpoints', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 59, name: 'London Eye Experience', fact: '30 minutes, 135 metres, 55 million visitors', location: 'Viewpoints', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 60, name: 'Thames Cable Car', fact: 'Aerial river crossing with docklands views for £4', location: 'Viewpoints', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 61, name: 'Windsor Castle', fact: "The world's oldest and largest occupied castle", location: 'Royal Palaces', category: 'WILD', isWildLocation: false, isWildCategory: true },
  { id: 62, name: 'National Portrait Gallery', fact: 'Every famous British face, from Tudors to today', location: 'Museums & Galleries', category: 'WILD', isWildLocation: false, isWildCategory: true },
  { id: 63, name: "St Paul's Cathedral", fact: "Wren's masterpiece — 365 steps to the Golden Gallery", location: 'Historic Landmarks', category: 'WILD', isWildLocation: false, isWildCategory: true },
  { id: 64, name: 'Royal Opera House', fact: 'World-class ballet and opera since 1732', location: 'Theatres & Entertainment', category: 'WILD', isWildLocation: false, isWildCategory: true },
  { id: 65, name: 'The View from The Shard', fact: 'on clear days you can see 40 miles', location: 'Viewpoints', category: 'WILD', isWildLocation: false, isWildCategory: true },
  { id: 66, name: 'Kew Gardens', fact: '50,000 living plants in a UNESCO World Heritage site', location: 'WILD', category: 'Parks & Gardens', isWildLocation: true, isWildCategory: false },
  { id: 67, name: 'Portobello Road Market', fact: "World's largest antiques market, every Saturday", location: 'WILD', category: 'Markets', isWildLocation: true, isWildCategory: false },
  { id: 68, name: 'Soho', fact: "From bohemian to brilliant — London's beating heart", location: 'WILD', category: 'Neighbourhoods', isWildLocation: true, isWildCategory: false },
  { id: 69, name: 'Westminster Pier', fact: 'Gateway to the Thames — every river trip starts here', location: 'WILD', category: 'River & Water', isWildLocation: true, isWildCategory: false },
  { id: 70, name: 'St John Restaurant', fact: 'Nose-to-tail dining that changed British food forever', location: 'WILD', category: 'Food & Dining', isWildLocation: true, isWildCategory: false },
  { id: 71, name: 'Rules Restaurant', fact: "London's oldest restaurant, serving since 1798", location: 'Historic Landmarks', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 72, name: 'Bunhill Fields', fact: 'Defoe, Blake, and Bunyan in a hidden city garden', location: 'Historic Landmarks', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 73, name: 'HMS Belfast', fact: 'WWII warship museum moored on the Thames since 1971', location: 'Historic Landmarks', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 74, name: 'Bermondsey Antiques Market', fact: 'Dawn dealers\' market — bargains before breakfast', location: 'Museums & Galleries', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 75, name: 'Maltby Street Market', fact: 'Railway arch foodie haven with gallery pop-ups', location: 'Museums & Galleries', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 76, name: 'Dulwich Picture Gallery', fact: "England's first purpose-built public gallery, 1817", location: 'Museums & Galleries', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 77, name: 'Serpentine Gallery', fact: 'Free contemporary art in the heart of Hyde Park', location: 'Museums & Galleries', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 78, name: 'National Maritime Museum', fact: "World's largest maritime museum, free to enter", location: 'Museums & Galleries', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 79, name: 'Battersea Power Station', fact: 'Art deco icon reborn as shops and galleries', location: 'Museums & Galleries', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 80, name: 'Regency Café', fact: 'Classic greasy spoon with Grade II listed interior', location: 'Royal Palaces', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 81, name: 'Royal Exchange', fact: 'Former trading floor, now luxury shops and dining', location: 'Royal Palaces', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 82, name: 'Kensington Palace Orangery', fact: 'Royal gifts and souvenirs in palace grounds', location: 'Royal Palaces', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 83, name: "St James's", fact: "London's most regal neighbourhood since the 1660s", location: 'Royal Palaces', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 84, name: 'Hampton Court Gardens', fact: "Henry VIII's maze — lost since 1690", location: 'Royal Palaces', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 85, name: 'Tower Wharf', fact: 'Crown Jewels arrived here by barge for 900 years', location: 'Royal Palaces', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 86, name: 'Columbia Road Market', fact: 'Sunday blooms and buskers in the East End', location: 'Theatres & Entertainment', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 87, name: 'Camden Town', fact: "Punk, rock, and rebellion on London's wildest street", location: 'Theatres & Entertainment', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 88, name: 'Peckham', fact: "South London's creative hub with rooftop cinema", location: 'Theatres & Entertainment', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 89, name: 'Kew Palace Concerts', fact: 'Summer music in the Royal Botanic Gardens', location: 'Theatres & Entertainment', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 90, name: 'Kenwood House Concerts', fact: 'Lakeside concerts on Hampstead Heath since 1951', location: 'Theatres & Entertainment', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 91, name: 'Floating Cinema', fact: 'Films screened from a narrowboat on the canal', location: 'Theatres & Entertainment', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 92, name: 'Pub on the Park', fact: 'Victoria Park comedy by the boating lake', location: 'Theatres & Entertainment', category: 'River & Water', isWildLocation: false, isWildCategory: false },
  { id: 93, name: 'Searcys at the Gherkin', fact: "Champagne at the top of London's favourite pickle", location: 'Viewpoints', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 94, name: 'Madison Rooftop', fact: "Open-air terrace overlooking St Paul's dome", location: 'Viewpoints', category: 'Food & Dining', isWildLocation: false, isWildCategory: false },
  { id: 95, name: 'Skylight Tobacco Dock', fact: 'Rooftop bar above a converted 19th-century warehouse', location: 'Viewpoints', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 96, name: 'Netil360 Rooftop', fact: 'Hackney rooftop with skyline views and vintage stalls', location: 'Viewpoints', category: 'Markets', isWildLocation: false, isWildCategory: false },
  { id: 97, name: 'Alexandra Palace', fact: "The People's Palace — panoramic views since 1873", location: 'Viewpoints', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 98, name: 'Stave Hill Ecology Park', fact: 'Hidden hilltop with surprise Canary Wharf views', location: 'Viewpoints', category: 'Neighbourhoods', isWildLocation: false, isWildCategory: false },
  { id: 99, name: 'Parliament Hill', fact: 'Kite-flying summit with a protected city panorama', location: 'Viewpoints', category: 'Parks & Gardens', isWildLocation: false, isWildCategory: false },
  { id: 100, name: 'Waterloo Bridge', fact: 'The finest bridge view in London — both directions', location: 'Viewpoints', category: 'River & Water', isWildLocation: false, isWildCategory: false },
];
